/**
 * @file    fm_main.c
 * @brief   Application entry point and main execution loop.
 *
 * @date    2026-02-28
 * @author  Daniel H Sagarra
 *
 * @details
 *  - Initializes board and debug services.
 *  - Demonstrates deferred debug logging from an RTC wakeup ISR.
 *  - Main loop flushes queued debug events in foreground context.
 *  - ISR measures wakeup period and jitter using DWT timestamps.
 */

/* ===========================     Includes    ============================== */
#include "main.h"
#include "fm_main.h"
#include "fm_debug.h"
#include "fm_board.h"
#include "tim.h"

/* =========================== Private Defines ============================== */
/**
 * @brief Event code used for RTC wakeup jitter measurements.
 *
 * Event payload:
 * - param0: measured interrupt period in CPU cycles
 * - param1: signed jitter in CPU cycles
 */
#define FM_MAIN_EVT_RTC_JITTER   (FM_DEBUG_EVT_USER + 1U)

/**
 * @brief Expected RTC wakeup period in CPU cycles.
 *
 * Example value for a 1 s period at 10 MHz DWT/CPU clock.
 * Replace with a board-specific conversion if clock changes dynamically.
 */
#define EXPECTED_CYCLES      	240000
#define JITTER_THRESHOLD_CYCLES 1

/* =========================== Private Types ================================ */
/* (none) */

/* =========================== Private Data ================================= */
/**
 * @brief Foreground notification flag set by the RTC ISR.
 *
 * Used only to wake the main loop so it can flush deferred debug events.
 */
static volatile bool rtc_flag = false;
static TIM_HandleTypeDef htim6;


/* =========================== Private Prototypes =========================== */
/* (none) */

/* =========================== Private Bodies =============================== */

void TIM7_Init(void)
{

  htim7.Instance = TIM7;

  // 24Mhz / 24000 = 1kHz
  htim7.Init.Prescaler = 23999;

  htim7.Init.CounterMode = TIM_COUNTERMODE_UP;

  // 1kHz / 10 = 10ms
  htim7.Init.Period = 9;

  htim7.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_DISABLE;
  if (HAL_TIM_Base_Init(&htim7) != HAL_OK)
  {
    Error_Handler();
  }

    __HAL_RCC_TIM7_CLK_ENABLE();

    HAL_NVIC_SetPriority(TIM7_IRQn, 6, 0);
    HAL_NVIC_EnableIRQ(TIM7_IRQn);
    HAL_TIM_Base_Start_IT(&htim7);
}

void TIM6_Init(void)
{

  htim6.Instance = TIM6;

  // 24Mhz / 239 = 100kHz
  htim6.Init.Prescaler = 2399;

  htim6.Init.CounterMode = TIM_COUNTERMODE_UP;

  // 100kHz / 100 = 1ms
  htim6.Init.Period = 99;

  htim6.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_DISABLE;
  if (HAL_TIM_Base_Init(&htim6) != HAL_OK)
  {
    Error_Handler();
  }

    __HAL_RCC_TIM6_CLK_ENABLE();

    HAL_NVIC_SetPriority(TIM6_IRQn, 5, 0);
    HAL_NVIC_EnableIRQ(TIM6_IRQn);
    HAL_TIM_Base_Start_IT(&htim6);
}



/* =========================== Public Bodies ================================ */
/**
 * @brief Initialize board services and jitter measurement state.
 *
 * Initializes the board layer first, then the debug module, and finally
 * prepares local state used by the RTC jitter example.
 */
void FM_MAIN_Init(void)
{
    FM_BOARD_Init();
    FM_DEBUG_Init();
    TIM7_Init();
    TIM6_Init();
    rtc_flag = false;
}

/**
 * @brief Main application loop.
 *
 * Waits for RTC wakeup notifications from the ISR and flushes any deferred
 * debug events from foreground context.
 *
 * @note FM_DEBUG_Flush() is intentionally executed outside interrupt context
 *       because it performs formatting and blocking UART transmission.
 */
void FM_MAIN_Main(void)
{
	static uint32_t drooped_last = 0;
	static const char MSG_LOG_OVERFLOW[] = "Dropped events since last flush: ";

    FM_MAIN_Init();

    for (;;)
    {
        while (!rtc_flag)
        {
            __NOP();
        }

        rtc_flag = false;
        FM_DEBUG_Flush();

        uint32_t drooped_now = FM_DEBUG_DroppedCount();
        uint32_t drooped_since_last = drooped_now - drooped_last;

        if(drooped_since_last)
		{
        	FM_DEBUG_UartMsg(MSG_LOG_OVERFLOW, sizeof(MSG_LOG_OVERFLOW) - 1);
			FM_DEBUG_UartInt32(drooped_since_last);
		}

        drooped_last = drooped_now;
    }
}

/* =========================== Interrupts =================================== */


void TIM6_IRQHandler(void)
{
	if (TIM6->SR & TIM_SR_UIF)
    {

        TIM6->SR &= ~TIM_SR_UIF;
        for(uint32_t wait = 400; wait; wait --)
        {
        	__NOP();
        }
    }
}



/**
 * @brief TIM7 global interrupt handler.
 *
 * @details
 * This ISR handles the Update Event (UEV) generated by TIM7.
 * The Update Event is triggered when the timer counter overflows
 * (i.e., reaches ARR and rolls over).
 *
 * Instead of relying on HAL's generic interrupt dispatcher
 * (HAL_TIM_IRQHandler), this implementation directly accesses
 * peripheral registers in order to:
 *
 * - Reduce latency
 * - Avoid shared/global callback dispatching
 * - Keep timer ownership within the application layer
 *
 * Execution flow:
 * 1. Check if Update Interrupt Flag (UIF) is set
 * 2. Clear UIF to acknowledge the interrupt
 * 3. Call application-specific handler
 *
 * @note
 * - This handler assumes TIM7 is configured in basic timer mode.
 * - Only Update events are handled here.
 * - No HAL functions are used intentionally.
 *
 * @warning
 * Failing to clear UIF will result in continuous re-entry into this ISR.
 *
 * @see FM_MAIN_IRQHandlerTIM7
 */
void TIM7_IRQHandler(void)
{
	/**
	 * @brief Indicates whether a previous timestamp is available.
	 * The first interrupt only initializes the measurement baseline.
	 */
	static bool jitter_ready = false;
	static bool toogle_led_signal;
	static uint32_t cycles_last = 0U;

    /**
     * @brief Check Update Interrupt Flag (UIF)
     *
     * TIM7->SR (Status Register):
     * - UIF bit indicates that an update event occurred
     *
     * Condition:
     * - Interrupt is pending only if UIF == 1
     */
    if (TIM7->SR & TIM_SR_UIF)
    {
        /**
         * @brief Clear Update Interrupt Flag
         *
         * Writing 0 to UIF clears the interrupt condition.
         * This must be done before exiting the ISR.
         */
        TIM7->SR &= ~TIM_SR_UIF;
        const uint32_t cycles_now = FM_DEBUG_TimestampCycles();

        /* First sample establishes the timing baseline only. */
        if (!jitter_ready)
        {
            cycles_last = cycles_now;
            jitter_ready = true;
            return;
        }

        const uint32_t cycles_delta = cycles_now - cycles_last;
        cycles_last = cycles_now;

        const int32_t cycles_jitter = (int32_t)cycles_delta - (uint32_t)EXPECTED_CYCLES;

        if((cycles_jitter > JITTER_THRESHOLD_CYCLES) || (cycles_jitter < -JITTER_THRESHOLD_CYCLES))
        {
			FM_DEBUG_Log2ISR(FM_MAIN_EVT_RTC_JITTER, (int32_t)cycles_delta, cycles_jitter);
			toogle_led_signal ^= 1;
			FM_DEBUG_LedSignal(toogle_led_signal);
        }
    }
}


/**
 * @brief RTC wakeup callback used to continue infinite loop.
 *
 */
void HAL_RTCEx_WakeUpTimerEventCallback(RTC_HandleTypeDef *hrtc)
{

    UNUSED(hrtc);
    rtc_flag = true;
}

/*** end of file ***/
